#!/usr/bin/python
###################################
import sys
import json
import urllib2
import urllib
##################################
variabletarget=raw_input("What language do you want to translate to...: ")
variablesource=raw_input("What language do you want to Translate from...: ")
##################################
key="AIzaSyDOq5348qab8-5UfwxXfiUdqnutGILyn4s"
##################################
url='https://www.googleapis.com/language/translate/v2?key='+key+'&q='+urllib.quote(sys.argv[1])+'&source='+variablesource+'&target='+variabletarget
##################################
handle=urllib2.urlopen(url)
readhandle=handle.read()
print (json.loads(readhandle))["data"]["translations"][0]["translatedText"] 
handle.close()
#################################
