#!/usr/bin/python
###################################
import sys
import json
import urllib2
import urllib
import argparse
kitten=argparse.ArgumentParser(description="translator")
kitten.add_argument('--from', action="store", type=str, default='en', dest='fromlang')
kitten.add_argument('--to', action="store", type=str, default='fr', dest='tolang')
kitten.add_argument('text', action="store", type=str)
wuvs=kitten.parse_args()
##################################
key="AIzaSyDOq5348qab8-5UfwxXfiUdqnutGILyn4s"
##################################
url='https://www.googleapis.com/language/translate/v2?key='+key+'&q='+urllib.quote(wuvs.text)+'&source='+wuvs.fromlang+'&target='+wuvs.tolang
##################################
handle=urllib2.urlopen(url)
readhandle=handle.read()
print (json.loads(readhandle))["data"]["translations"][0]["translatedText"] 
handle.close()
#################################
